Feat: 자기소개 페이지 완성1
Konkuk-KUIT/KUIT3_Web-FrontEnd pull request #20
Opened 2024-03-22 08:08 UTC by brian770

1주차 과제 제출합니다.

2024-03-22 10:02 UTC, Nangniya requested changes

2024-03-22 10:02 UTC, Nangniya commented on week1/seongyou/index.html
> +</body>
body에 내용이 없어요!!

2024-03-28 16:11 UTC, brian770 commented on week1/seongyou/index.html
> +</body>
수정해서 커밋했습니다!

2024-04-07 05:25 UTC, Nangniya requested changes
수정은 잘 됩니다!
그런데 week3도 폴더를 jinho1011에 하시면 안되고 
week3 하위에 자기 폴더를 만들어서 새로 해주세요! 
week3/seongyou

2024-04-07 05:30 UTC, Nangniya commented
새로 만드시고 jinho1011 폴더는 원래대로 돌려놓으시거나 삭제 해주셔야합니다!

2024-05-04 04:10 UTC, Nangniya requested changes
미션은 잘 수행해주셨습니다.
하지만 각 주차별 꼭 본인 폴더를 만들어서 본인 폴더에만 작업해주세요!!
계속 충돌이 일어나서 merge를 못하고있습니다 ㅠㅠ 
수정 부탁드립니다.

2024-05-08 11:53 UTC, Nangniya approved these changes

2024-05-08 11:53 UTC, merged