Feat: 2주차 미션 제출
Konkuk-KUIT/KUIT3_Web-FrontEnd pull request #34
Opened 2024-03-29 08:04 UTC by YongChanCho

![2주차 당근 클론](https://github.com/Konkuk-KUIT/KUIT3_Web-FrontEnd/assets/127338463/fa56527f-5d20-47f7-9ccb-33937a63b6c4)

2주차 과제 제출합니다.

2024-03-29 13:10 UTC, crohasang commented on week2/index.css
> +.product1{
product1, product2, product3, .... 이렇게 각각 따로 속성을 주셨는데 이런 방법보다는

똑같이 product 클래스를 여러개 쓰고 이 클래스에게 padding이나 margin 같은 속성을 부여해서 product 간의 간격을 주는게 더 좋을 거 같아요!

2024-03-29 13:12 UTC, crohasang commented
폴더 이름을 week2가 아닌 week2/YongChanCho로 하고 제출해주시면 감사합니다!

2024-03-29 13:13 UTC, crohasang requested changes
폴더 이름을 week2가 아닌 week2/YongChanCho(혹은 본인을 나타낼 수 있는 이름)로 하고 제출해주시면 감사합니다!

2024-03-29 14:32 UTC, algoORgoal commented
![image](https://github.com/Konkuk-KUIT/KUIT3_Web-FrontEnd/assets/19303532/617b064b-a47e-4717-b5bd-8855934ee149)

바텀네비게이션 아래쪽에 컨텐츠가 살짝 보이는데, 이걸 가리면 더 좋을 것 같아요.

2024-03-30 06:11 UTC, YongChanCho commented on week2/index.css
> +.product1{
옙 피드백 감사합니다 ㅎㅎ

2024-03-30 06:14 UTC, closed without merging