Feat: 당근마켓 페이지 2주차 미션
Konkuk-KUIT/KUIT3_Web-FrontEnd pull request #35
Opened 2024-03-29 08:58 UTC by yskim6772

2024-03-29 23:31 UTC, crohasang commented on week2_ys/week2.css
> +    font-style: normal;
font-family: Inter, font-style: normal이 여러 요소에서 반복되어서 선언되고 있어요!
상위 요소에 선언해서 중복을 줄여보는 것도 괜찮을 것 같습니다!

2024-03-29 23:33 UTC, crohasang approved these changes
코드 잘 작성해주셨습니다. 수고 많으셨어요!!

2024-03-29 23:46 UTC, crohasang requested changes
현재 폴더가 week2_ys로 되있는데 week2 폴더를 생성하고 그 안에 폴더를 week2_ys(혹은 다른이름)으로 만들어서 커밋하시는 것이 더 좋을 것 같아요!

2024-04-01 11:06 UTC, Nangniya approved these changes

2024-04-01 11:07 UTC, Nangniya approved these changes
수고하셨습니다! 잘 구현해주셨어요 👍

2024-04-01 11:08 UTC, merged