Feat: 3주차 미션 제출
Konkuk-KUIT/KUIT3_Web-FrontEnd pull request #47
Opened 2024-04-05 10:09 UTC by yskim6772

3주차 미션 제출합니다.

2024-04-05 12:32 UTC, Nangniya requested changes

2024-04-05 12:32 UTC, Nangniya commented on week3/yoonseo/app.js
> +    const newTitle = document.createElement("new");
"new"는 HTML 태그 이름이 아니라서 DOM객체가 생성되지 않습니다! 
여기서 생성이 되지 않아서 뒤에 코드가 실행이 되지 않고 있습니다.

2024-04-07 05:33 UTC, yskim6772 commented on week3/yoonseo/app.js
> +    const newTitle = document.createElement("new");
코드 수정 완료했습니다! 확인 부탁드립니당

2024-04-07 05:37 UTC, Nangniya approved these changes
수정 잘 됩니다!

2024-04-07 05:37 UTC, merged