Feat:5주차 미션
Konkuk-KUIT/KUIT3_Web-FrontEnd pull request #75
Opened 2024-05-02 06:25 UTC by YongChanCho

5주차 미션 완료!

2024-05-02 13:23 UTC, Jinho1011 commented
`/node_modules`를 .gitignore에 추가해주세요

2024-05-03 11:00 UTC, Nangniya requested changes
디스코드 공지 참고하셔서 node_modules를 제거하고 다시 올려주세요!

2024-05-10 11:23 UTC, Nangniya requested changes
미션 잘 수행해주셨습니다! node_modules만 제거해서 다시 올려주세요

2024-05-10 11:23 UTC, Nangniya commented on week5/.gitignore
> +/node_modules
```suggestion
node_modules/
```
이렇게 해야 node_moduels가 안올라온다고 합니다. 
그리고 .gitignore는 올라오기 전에 방지해주는거라 이미 올라온 node_modules는 제거해서 다시 올려주셔야합니다 ㅠㅠ

2024-05-10 12:03 UTC, YongChanCho commented on week5/.gitignore
> +/node_modules
아아 넵 알겠습니다

2024-05-13 05:16 UTC, Nangniya approved these changes

2024-05-13 05:16 UTC, Nangniya commented on week6/src/components/ProductRow.tsx
> +      <button onClick={handleDeleteBtn} type="button" aria-label="삭제">🗑️</button>
aria-label 사용 굿입니다 👍

2024-05-13 05:16 UTC, merged